{
 "title": "Traffic Monitor Malioboro",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Traffic Monitoring Malioboro Street Dashboard"
   }
  },
  {
   "title": "Total Kendaraan Hari Ini",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\nCOALESCE(SUM(total),0)\r\nFROM traffic_logs\r\nWHERE timestamp::date=CURRENT_DATE;"
    }
   ]
  },
  {
   "title": "Rata-rata Kendaraan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\nROUND(AVG(total),2)\r\nFROM traffic_logs;"
    }
   ]
  },
  {
   "title": "Peak Traffic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\nMAX(total)\r\nFROM traffic_logs;"
    }
   ]
  },
  {
   "title": "Active Camera",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\nCOUNT(DISTINCT camera_id)\r\nFROM traffic_logs;"
    }
   ]
  },
  {
   "title": "Traffic Trend",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\n\r\ndate_trunc('minute',timestamp) as time,\r\n\r\nAVG(total) as vehicle_count\r\n\r\nFROM traffic_logs\r\n\r\nGROUP BY 1\r\n\r\nORDER BY 1;"
    }
   ]
  },
  {
   "title": "Distribusi Jenis Kendaraan",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(car) AS car, SUM(motorcycle) AS motorcycle, SUM(bus) AS bus, SUM(truck) AS truck FROM traffic_logs"
    }
   ]
  },
  {
   "title": "Weekday vs Weekend",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 13 },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\n\r\nCASE\r\n\r\nWHEN EXTRACT(ISODOW FROM timestamp)<=5\r\n\r\nTHEN 'Weekday'\r\n\r\nELSE 'Weekend'\r\n\r\nEND day_type,\r\n\r\nAVG(total)\r\n\r\nFROM traffic_logs\r\n\r\nGROUP BY day_type;"
    }
   ]
  },
  {
   "title": "Recent Detection",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "dataset": "traffic_db",
     "rawSql": "SELECT\r\n\r\ntimestamp,\r\n\r\ncamera_id,\r\n\r\ncar,\r\n\r\nmotorcycle,\r\n\r\nbus,\r\n\r\ntruck,\r\n\r\ntotal\r\n\r\nFROM traffic_logs\r\n\r\nORDER BY timestamp DESC\r\n\r\nLIMIT 20;"
    }
   ]
  }
 ]
}